// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: pkg/analyzer/commit_analyzer.proto

package analyzer

import (
	semrel "github.com/go-semantic-release/semantic-release/pkg/semrel"
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CommitAnalyzerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RawCommits []*semrel.RawCommit `protobuf:"bytes,1,rep,name=RawCommits,proto3" json:"RawCommits,omitempty"`
}

func (x *CommitAnalyzerRequest) Reset() {
	*x = CommitAnalyzerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_analyzer_commit_analyzer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitAnalyzerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitAnalyzerRequest) ProtoMessage() {}

func (x *CommitAnalyzerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_analyzer_commit_analyzer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitAnalyzerRequest.ProtoReflect.Descriptor instead.
func (*CommitAnalyzerRequest) Descriptor() ([]byte, []int) {
	return file_pkg_analyzer_commit_analyzer_proto_rawDescGZIP(), []int{0}
}

func (x *CommitAnalyzerRequest) GetRawCommits() []*semrel.RawCommit {
	if x != nil {
		return x.RawCommits
	}
	return nil
}

type CommitAnalyzerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Commits []*semrel.Commit `protobuf:"bytes,1,rep,name=Commits,proto3" json:"Commits,omitempty"`
}

func (x *CommitAnalyzerResponse) Reset() {
	*x = CommitAnalyzerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_analyzer_commit_analyzer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitAnalyzerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitAnalyzerResponse) ProtoMessage() {}

func (x *CommitAnalyzerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_analyzer_commit_analyzer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitAnalyzerResponse.ProtoReflect.Descriptor instead.
func (*CommitAnalyzerResponse) Descriptor() ([]byte, []int) {
	return file_pkg_analyzer_commit_analyzer_proto_rawDescGZIP(), []int{1}
}

func (x *CommitAnalyzerResponse) GetCommits() []*semrel.Commit {
	if x != nil {
		return x.Commits
	}
	return nil
}

var File_pkg_analyzer_commit_analyzer_proto protoreflect.FileDescriptor

var file_pkg_analyzer_commit_analyzer_proto_rawDesc = []byte{
	0x0a, 0x22, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x72, 0x2f, 0x63,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x5f, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x18, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x65, 0x6d, 0x72, 0x65, 0x6c,
	0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x43,
	0x0a, 0x15, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x0a, 0x52, 0x61, 0x77, 0x43, 0x6f,
	0x6d, 0x6d, 0x69, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x52, 0x61,
	0x77, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x0a, 0x52, 0x61, 0x77, 0x43, 0x6f, 0x6d, 0x6d,
	0x69, 0x74, 0x73, 0x22, 0x3b, 0x0a, 0x16, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x41, 0x6e, 0x61,
	0x6c, 0x79, 0x7a, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a,
	0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x73,
	0x32, 0x52, 0x0a, 0x14, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x7a,
	0x65, 0x72, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x12, 0x3a, 0x0a, 0x07, 0x41, 0x6e, 0x61, 0x6c,
	0x79, 0x7a, 0x65, 0x12, 0x16, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x41, 0x6e, 0x61, 0x6c,
	0x79, 0x7a, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x43, 0x6f,
	0x6d, 0x6d, 0x69, 0x74, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3e, 0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x2d, 0x73, 0x65, 0x6d, 0x61, 0x6e, 0x74, 0x69, 0x63, 0x2d, 0x72,
	0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x2f, 0x73, 0x65, 0x6d, 0x61, 0x6e, 0x74, 0x69, 0x63, 0x2d,
	0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x6e, 0x61, 0x6c,
	0x79, 0x7a, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_analyzer_commit_analyzer_proto_rawDescOnce sync.Once
	file_pkg_analyzer_commit_analyzer_proto_rawDescData = file_pkg_analyzer_commit_analyzer_proto_rawDesc
)

func file_pkg_analyzer_commit_analyzer_proto_rawDescGZIP() []byte {
	file_pkg_analyzer_commit_analyzer_proto_rawDescOnce.Do(func() {
		file_pkg_analyzer_commit_analyzer_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_analyzer_commit_analyzer_proto_rawDescData)
	})
	return file_pkg_analyzer_commit_analyzer_proto_rawDescData
}

var file_pkg_analyzer_commit_analyzer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_analyzer_commit_analyzer_proto_goTypes = []interface{}{
	(*CommitAnalyzerRequest)(nil),  // 0: CommitAnalyzerRequest
	(*CommitAnalyzerResponse)(nil), // 1: CommitAnalyzerResponse
	(*semrel.RawCommit)(nil),       // 2: RawCommit
	(*semrel.Commit)(nil),          // 3: Commit
}
var file_pkg_analyzer_commit_analyzer_proto_depIdxs = []int32{
	2, // 0: CommitAnalyzerRequest.RawCommits:type_name -> RawCommit
	3, // 1: CommitAnalyzerResponse.Commits:type_name -> Commit
	0, // 2: CommitAnalyzerPlugin.Analyze:input_type -> CommitAnalyzerRequest
	1, // 3: CommitAnalyzerPlugin.Analyze:output_type -> CommitAnalyzerResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_analyzer_commit_analyzer_proto_init() }
func file_pkg_analyzer_commit_analyzer_proto_init() {
	if File_pkg_analyzer_commit_analyzer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_analyzer_commit_analyzer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommitAnalyzerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_analyzer_commit_analyzer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommitAnalyzerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_analyzer_commit_analyzer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_analyzer_commit_analyzer_proto_goTypes,
		DependencyIndexes: file_pkg_analyzer_commit_analyzer_proto_depIdxs,
		MessageInfos:      file_pkg_analyzer_commit_analyzer_proto_msgTypes,
	}.Build()
	File_pkg_analyzer_commit_analyzer_proto = out.File
	file_pkg_analyzer_commit_analyzer_proto_rawDesc = nil
	file_pkg_analyzer_commit_analyzer_proto_goTypes = nil
	file_pkg_analyzer_commit_analyzer_proto_depIdxs = nil
}
