// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: pkg/hooks/hooks.proto

package hooks

import (
	provider "github.com/go-semantic-release/semantic-release/v2/pkg/provider"
	semrel "github.com/go-semantic-release/semantic-release/v2/pkg/semrel"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NoReleaseReason int32

const (
	NoReleaseReason_CONDITION NoReleaseReason = 0
	NoReleaseReason_NO_CHANGE NoReleaseReason = 1
)

// Enum value maps for NoReleaseReason.
var (
	NoReleaseReason_name = map[int32]string{
		0: "CONDITION",
		1: "NO_CHANGE",
	}
	NoReleaseReason_value = map[string]int32{
		"CONDITION": 0,
		"NO_CHANGE": 1,
	}
)

func (x NoReleaseReason) Enum() *NoReleaseReason {
	p := new(NoReleaseReason)
	*p = x
	return p
}

func (x NoReleaseReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NoReleaseReason) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_hooks_hooks_proto_enumTypes[0].Descriptor()
}

func (NoReleaseReason) Type() protoreflect.EnumType {
	return &file_pkg_hooks_hooks_proto_enumTypes[0]
}

func (x NoReleaseReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NoReleaseReason.Descriptor instead.
func (NoReleaseReason) EnumDescriptor() ([]byte, []int) {
	return file_pkg_hooks_hooks_proto_rawDescGZIP(), []int{0}
}

type HooksInit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HooksInit) Reset() {
	*x = HooksInit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_hooks_hooks_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HooksInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HooksInit) ProtoMessage() {}

func (x *HooksInit) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hooks_hooks_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HooksInit.ProtoReflect.Descriptor instead.
func (*HooksInit) Descriptor() ([]byte, []int) {
	return file_pkg_hooks_hooks_proto_rawDescGZIP(), []int{0}
}

type HooksName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HooksName) Reset() {
	*x = HooksName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_hooks_hooks_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HooksName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HooksName) ProtoMessage() {}

func (x *HooksName) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hooks_hooks_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HooksName.ProtoReflect.Descriptor instead.
func (*HooksName) Descriptor() ([]byte, []int) {
	return file_pkg_hooks_hooks_proto_rawDescGZIP(), []int{1}
}

type HooksVersion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HooksVersion) Reset() {
	*x = HooksVersion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_hooks_hooks_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HooksVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HooksVersion) ProtoMessage() {}

func (x *HooksVersion) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hooks_hooks_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HooksVersion.ProtoReflect.Descriptor instead.
func (*HooksVersion) Descriptor() ([]byte, []int) {
	return file_pkg_hooks_hooks_proto_rawDescGZIP(), []int{2}
}

type SuccessHookConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Commits     []*semrel.Commit         `protobuf:"bytes,1,rep,name=commits,proto3" json:"commits,omitempty"`
	PrevRelease *semrel.Release          `protobuf:"bytes,2,opt,name=prev_release,json=prevRelease,proto3" json:"prev_release,omitempty"`
	NewRelease  *semrel.Release          `protobuf:"bytes,3,opt,name=new_release,json=newRelease,proto3" json:"new_release,omitempty"`
	Changelog   string                   `protobuf:"bytes,4,opt,name=changelog,proto3" json:"changelog,omitempty"`
	RepoInfo    *provider.RepositoryInfo `protobuf:"bytes,5,opt,name=repo_info,json=repoInfo,proto3" json:"repo_info,omitempty"`
}

func (x *SuccessHookConfig) Reset() {
	*x = SuccessHookConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_hooks_hooks_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SuccessHookConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessHookConfig) ProtoMessage() {}

func (x *SuccessHookConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hooks_hooks_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessHookConfig.ProtoReflect.Descriptor instead.
func (*SuccessHookConfig) Descriptor() ([]byte, []int) {
	return file_pkg_hooks_hooks_proto_rawDescGZIP(), []int{3}
}

func (x *SuccessHookConfig) GetCommits() []*semrel.Commit {
	if x != nil {
		return x.Commits
	}
	return nil
}

func (x *SuccessHookConfig) GetPrevRelease() *semrel.Release {
	if x != nil {
		return x.PrevRelease
	}
	return nil
}

func (x *SuccessHookConfig) GetNewRelease() *semrel.Release {
	if x != nil {
		return x.NewRelease
	}
	return nil
}

func (x *SuccessHookConfig) GetChangelog() string {
	if x != nil {
		return x.Changelog
	}
	return ""
}

func (x *SuccessHookConfig) GetRepoInfo() *provider.RepositoryInfo {
	if x != nil {
		return x.RepoInfo
	}
	return nil
}

type SuccessHook struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SuccessHook) Reset() {
	*x = SuccessHook{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_hooks_hooks_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SuccessHook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessHook) ProtoMessage() {}

func (x *SuccessHook) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hooks_hooks_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessHook.ProtoReflect.Descriptor instead.
func (*SuccessHook) Descriptor() ([]byte, []int) {
	return file_pkg_hooks_hooks_proto_rawDescGZIP(), []int{4}
}

type NoReleaseConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason  NoReleaseReason `protobuf:"varint,1,opt,name=reason,proto3,enum=NoReleaseReason" json:"reason,omitempty"`
	Message string          `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *NoReleaseConfig) Reset() {
	*x = NoReleaseConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_hooks_hooks_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoReleaseConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoReleaseConfig) ProtoMessage() {}

func (x *NoReleaseConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hooks_hooks_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoReleaseConfig.ProtoReflect.Descriptor instead.
func (*NoReleaseConfig) Descriptor() ([]byte, []int) {
	return file_pkg_hooks_hooks_proto_rawDescGZIP(), []int{5}
}

func (x *NoReleaseConfig) GetReason() NoReleaseReason {
	if x != nil {
		return x.Reason
	}
	return NoReleaseReason_CONDITION
}

func (x *NoReleaseConfig) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type NoReleaseHook struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NoReleaseHook) Reset() {
	*x = NoReleaseHook{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_hooks_hooks_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoReleaseHook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoReleaseHook) ProtoMessage() {}

func (x *NoReleaseHook) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hooks_hooks_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoReleaseHook.ProtoReflect.Descriptor instead.
func (*NoReleaseHook) Descriptor() ([]byte, []int) {
	return file_pkg_hooks_hooks_proto_rawDescGZIP(), []int{6}
}

type HooksInit_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config map[string]string `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *HooksInit_Request) Reset() {
	*x = HooksInit_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_hooks_hooks_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HooksInit_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HooksInit_Request) ProtoMessage() {}

func (x *HooksInit_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hooks_hooks_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HooksInit_Request.ProtoReflect.Descriptor instead.
func (*HooksInit_Request) Descriptor() ([]byte, []int) {
	return file_pkg_hooks_hooks_proto_rawDescGZIP(), []int{0, 0}
}

func (x *HooksInit_Request) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type HooksInit_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *HooksInit_Response) Reset() {
	*x = HooksInit_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_hooks_hooks_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HooksInit_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HooksInit_Response) ProtoMessage() {}

func (x *HooksInit_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hooks_hooks_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HooksInit_Response.ProtoReflect.Descriptor instead.
func (*HooksInit_Response) Descriptor() ([]byte, []int) {
	return file_pkg_hooks_hooks_proto_rawDescGZIP(), []int{0, 1}
}

func (x *HooksInit_Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HooksName_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HooksName_Request) Reset() {
	*x = HooksName_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_hooks_hooks_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HooksName_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HooksName_Request) ProtoMessage() {}

func (x *HooksName_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hooks_hooks_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HooksName_Request.ProtoReflect.Descriptor instead.
func (*HooksName_Request) Descriptor() ([]byte, []int) {
	return file_pkg_hooks_hooks_proto_rawDescGZIP(), []int{1, 0}
}

type HooksName_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *HooksName_Response) Reset() {
	*x = HooksName_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_hooks_hooks_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HooksName_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HooksName_Response) ProtoMessage() {}

func (x *HooksName_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hooks_hooks_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HooksName_Response.ProtoReflect.Descriptor instead.
func (*HooksName_Response) Descriptor() ([]byte, []int) {
	return file_pkg_hooks_hooks_proto_rawDescGZIP(), []int{1, 1}
}

func (x *HooksName_Response) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HooksVersion_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HooksVersion_Request) Reset() {
	*x = HooksVersion_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_hooks_hooks_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HooksVersion_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HooksVersion_Request) ProtoMessage() {}

func (x *HooksVersion_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hooks_hooks_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HooksVersion_Request.ProtoReflect.Descriptor instead.
func (*HooksVersion_Request) Descriptor() ([]byte, []int) {
	return file_pkg_hooks_hooks_proto_rawDescGZIP(), []int{2, 0}
}

type HooksVersion_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *HooksVersion_Response) Reset() {
	*x = HooksVersion_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_hooks_hooks_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HooksVersion_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HooksVersion_Response) ProtoMessage() {}

func (x *HooksVersion_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hooks_hooks_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HooksVersion_Response.ProtoReflect.Descriptor instead.
func (*HooksVersion_Response) Descriptor() ([]byte, []int) {
	return file_pkg_hooks_hooks_proto_rawDescGZIP(), []int{2, 1}
}

func (x *HooksVersion_Response) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type SuccessHook_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config *SuccessHookConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *SuccessHook_Request) Reset() {
	*x = SuccessHook_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_hooks_hooks_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SuccessHook_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessHook_Request) ProtoMessage() {}

func (x *SuccessHook_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hooks_hooks_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessHook_Request.ProtoReflect.Descriptor instead.
func (*SuccessHook_Request) Descriptor() ([]byte, []int) {
	return file_pkg_hooks_hooks_proto_rawDescGZIP(), []int{4, 0}
}

func (x *SuccessHook_Request) GetConfig() *SuccessHookConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type SuccessHook_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *SuccessHook_Response) Reset() {
	*x = SuccessHook_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_hooks_hooks_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SuccessHook_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessHook_Response) ProtoMessage() {}

func (x *SuccessHook_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hooks_hooks_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessHook_Response.ProtoReflect.Descriptor instead.
func (*SuccessHook_Response) Descriptor() ([]byte, []int) {
	return file_pkg_hooks_hooks_proto_rawDescGZIP(), []int{4, 1}
}

func (x *SuccessHook_Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type NoReleaseHook_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config *NoReleaseConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *NoReleaseHook_Request) Reset() {
	*x = NoReleaseHook_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_hooks_hooks_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoReleaseHook_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoReleaseHook_Request) ProtoMessage() {}

func (x *NoReleaseHook_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hooks_hooks_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoReleaseHook_Request.ProtoReflect.Descriptor instead.
func (*NoReleaseHook_Request) Descriptor() ([]byte, []int) {
	return file_pkg_hooks_hooks_proto_rawDescGZIP(), []int{6, 0}
}

func (x *NoReleaseHook_Request) GetConfig() *NoReleaseConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type NoReleaseHook_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *NoReleaseHook_Response) Reset() {
	*x = NoReleaseHook_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_hooks_hooks_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoReleaseHook_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoReleaseHook_Response) ProtoMessage() {}

func (x *NoReleaseHook_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hooks_hooks_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoReleaseHook_Response.ProtoReflect.Descriptor instead.
func (*NoReleaseHook_Response) Descriptor() ([]byte, []int) {
	return file_pkg_hooks_hooks_proto_rawDescGZIP(), []int{6, 1}
}

func (x *NoReleaseHook_Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_pkg_hooks_hooks_proto protoreflect.FileDescriptor

var file_pkg_hooks_hooks_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x6b, 0x67, 0x2f, 0x68, 0x6f, 0x6f, 0x6b, 0x73, 0x2f, 0x68, 0x6f, 0x6f, 0x6b,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x18, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x65, 0x6d,
	0x72, 0x65, 0x6c, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1b, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x2f,
	0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xab,
	0x01, 0x0a, 0x09, 0x48, 0x6f, 0x6f, 0x6b, 0x73, 0x49, 0x6e, 0x69, 0x74, 0x1a, 0x7c, 0x0a, 0x07,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x48, 0x6f, 0x6f, 0x6b, 0x73, 0x49,
	0x6e, 0x69, 0x74, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x1a,
	0x39, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x20, 0x0a, 0x08, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x36, 0x0a, 0x09,
	0x48, 0x6f, 0x6f, 0x6b, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x09, 0x0a, 0x07, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3f, 0x0a, 0x0c, 0x48, 0x6f, 0x6f, 0x6b, 0x73, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x1a, 0x09, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x24, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0xda, 0x01, 0x0a, 0x11, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x48, 0x6f, 0x6f, 0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x21, 0x0a, 0x07, 0x63,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x73, 0x12, 0x2b,
	0x0a, 0x0c, 0x70, 0x72, 0x65, 0x76, 0x5f, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x0b,
	0x70, 0x72, 0x65, 0x76, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x0b, 0x6e,
	0x65, 0x77, 0x5f, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x08, 0x2e, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x0a, 0x6e, 0x65, 0x77, 0x52,
	0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x6c, 0x6f, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x6c, 0x6f, 0x67, 0x12, 0x2c, 0x0a, 0x09, 0x72, 0x65, 0x70, 0x6f, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x72, 0x65, 0x70, 0x6f, 0x49, 0x6e,
	0x66, 0x6f, 0x22, 0x66, 0x0a, 0x0b, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x48, 0x6f, 0x6f,
	0x6b, 0x1a, 0x35, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x06,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x53,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x48, 0x6f, 0x6f, 0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x1a, 0x20, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x55, 0x0a, 0x0f, 0x4e, 0x6f,
	0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x28, 0x0a,
	0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e,
	0x4e, 0x6f, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x52,
	0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x66, 0x0a, 0x0d, 0x4e, 0x6f, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x48, 0x6f,
	0x6f, 0x6b, 0x1a, 0x33, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a,
	0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x4e, 0x6f, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52,
	0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x1a, 0x20, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2a, 0x2f, 0x0a, 0x0f, 0x4e, 0x6f, 0x52,
	0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x0d, 0x0a, 0x09,
	0x43, 0x4f, 0x4e, 0x44, 0x49, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x4e,
	0x4f, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x10, 0x01, 0x32, 0x9f, 0x02, 0x0a, 0x0b, 0x48,
	0x6f, 0x6f, 0x6b, 0x73, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x12, 0x2f, 0x0a, 0x04, 0x49, 0x6e,
	0x69, 0x74, 0x12, 0x12, 0x2e, 0x48, 0x6f, 0x6f, 0x6b, 0x73, 0x49, 0x6e, 0x69, 0x74, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x48, 0x6f, 0x6f, 0x6b, 0x73, 0x49, 0x6e,
	0x69, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x12, 0x2e, 0x48, 0x6f, 0x6f, 0x6b, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x48, 0x6f, 0x6f, 0x6b, 0x73, 0x4e,
	0x61, 0x6d, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x07,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x15, 0x2e, 0x48, 0x6f, 0x6f, 0x6b, 0x73, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16,
	0x2e, 0x48, 0x6f, 0x6f, 0x6b, 0x73, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x12, 0x14, 0x2e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x48, 0x6f, 0x6f, 0x6b, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x48, 0x6f, 0x6f, 0x6b, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c,
	0x0a, 0x09, 0x4e, 0x6f, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x12, 0x16, 0x2e, 0x4e, 0x6f,
	0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x48, 0x6f, 0x6f, 0x6b, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x4e, 0x6f, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x48,
	0x6f, 0x6f, 0x6b, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3e, 0x5a, 0x3c,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x2d, 0x73, 0x65,
	0x6d, 0x61, 0x6e, 0x74, 0x69, 0x63, 0x2d, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x2f, 0x73,
	0x65, 0x6d, 0x61, 0x6e, 0x74, 0x69, 0x63, 0x2d, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x2f,
	0x76, 0x32, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x68, 0x6f, 0x6f, 0x6b, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_hooks_hooks_proto_rawDescOnce sync.Once
	file_pkg_hooks_hooks_proto_rawDescData = file_pkg_hooks_hooks_proto_rawDesc
)

func file_pkg_hooks_hooks_proto_rawDescGZIP() []byte {
	file_pkg_hooks_hooks_proto_rawDescOnce.Do(func() {
		file_pkg_hooks_hooks_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_hooks_hooks_proto_rawDescData)
	})
	return file_pkg_hooks_hooks_proto_rawDescData
}

var file_pkg_hooks_hooks_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_hooks_hooks_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_pkg_hooks_hooks_proto_goTypes = []interface{}{
	(NoReleaseReason)(0),            // 0: NoReleaseReason
	(*HooksInit)(nil),               // 1: HooksInit
	(*HooksName)(nil),               // 2: HooksName
	(*HooksVersion)(nil),            // 3: HooksVersion
	(*SuccessHookConfig)(nil),       // 4: SuccessHookConfig
	(*SuccessHook)(nil),             // 5: SuccessHook
	(*NoReleaseConfig)(nil),         // 6: NoReleaseConfig
	(*NoReleaseHook)(nil),           // 7: NoReleaseHook
	(*HooksInit_Request)(nil),       // 8: HooksInit.Request
	(*HooksInit_Response)(nil),      // 9: HooksInit.Response
	nil,                             // 10: HooksInit.Request.ConfigEntry
	(*HooksName_Request)(nil),       // 11: HooksName.Request
	(*HooksName_Response)(nil),      // 12: HooksName.Response
	(*HooksVersion_Request)(nil),    // 13: HooksVersion.Request
	(*HooksVersion_Response)(nil),   // 14: HooksVersion.Response
	(*SuccessHook_Request)(nil),     // 15: SuccessHook.Request
	(*SuccessHook_Response)(nil),    // 16: SuccessHook.Response
	(*NoReleaseHook_Request)(nil),   // 17: NoReleaseHook.Request
	(*NoReleaseHook_Response)(nil),  // 18: NoReleaseHook.Response
	(*semrel.Commit)(nil),           // 19: Commit
	(*semrel.Release)(nil),          // 20: Release
	(*provider.RepositoryInfo)(nil), // 21: RepositoryInfo
}
var file_pkg_hooks_hooks_proto_depIdxs = []int32{
	19, // 0: SuccessHookConfig.commits:type_name -> Commit
	20, // 1: SuccessHookConfig.prev_release:type_name -> Release
	20, // 2: SuccessHookConfig.new_release:type_name -> Release
	21, // 3: SuccessHookConfig.repo_info:type_name -> RepositoryInfo
	0,  // 4: NoReleaseConfig.reason:type_name -> NoReleaseReason
	10, // 5: HooksInit.Request.config:type_name -> HooksInit.Request.ConfigEntry
	4,  // 6: SuccessHook.Request.config:type_name -> SuccessHookConfig
	6,  // 7: NoReleaseHook.Request.config:type_name -> NoReleaseConfig
	8,  // 8: HooksPlugin.Init:input_type -> HooksInit.Request
	11, // 9: HooksPlugin.Name:input_type -> HooksName.Request
	13, // 10: HooksPlugin.Version:input_type -> HooksVersion.Request
	15, // 11: HooksPlugin.Success:input_type -> SuccessHook.Request
	17, // 12: HooksPlugin.NoRelease:input_type -> NoReleaseHook.Request
	9,  // 13: HooksPlugin.Init:output_type -> HooksInit.Response
	12, // 14: HooksPlugin.Name:output_type -> HooksName.Response
	14, // 15: HooksPlugin.Version:output_type -> HooksVersion.Response
	16, // 16: HooksPlugin.Success:output_type -> SuccessHook.Response
	18, // 17: HooksPlugin.NoRelease:output_type -> NoReleaseHook.Response
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_pkg_hooks_hooks_proto_init() }
func file_pkg_hooks_hooks_proto_init() {
	if File_pkg_hooks_hooks_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_hooks_hooks_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HooksInit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_hooks_hooks_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HooksName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_hooks_hooks_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HooksVersion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_hooks_hooks_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SuccessHookConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_hooks_hooks_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SuccessHook); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_hooks_hooks_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoReleaseConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_hooks_hooks_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoReleaseHook); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_hooks_hooks_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HooksInit_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_hooks_hooks_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HooksInit_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_hooks_hooks_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HooksName_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_hooks_hooks_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HooksName_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_hooks_hooks_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HooksVersion_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_hooks_hooks_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HooksVersion_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_hooks_hooks_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SuccessHook_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_hooks_hooks_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SuccessHook_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_hooks_hooks_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoReleaseHook_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_hooks_hooks_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoReleaseHook_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_hooks_hooks_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_hooks_hooks_proto_goTypes,
		DependencyIndexes: file_pkg_hooks_hooks_proto_depIdxs,
		EnumInfos:         file_pkg_hooks_hooks_proto_enumTypes,
		MessageInfos:      file_pkg_hooks_hooks_proto_msgTypes,
	}.Build()
	File_pkg_hooks_hooks_proto = out.File
	file_pkg_hooks_hooks_proto_rawDesc = nil
	file_pkg_hooks_hooks_proto_goTypes = nil
	file_pkg_hooks_hooks_proto_depIdxs = nil
}
