// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: pkg/provider/provider.proto

package provider

import (
	_ "github.com/go-semantic-release/semantic-release/pkg/semrel"
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RepositoryInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Owner         string `protobuf:"bytes,1,opt,name=Owner,proto3" json:"Owner,omitempty"`
	Repo          string `protobuf:"bytes,2,opt,name=Repo,proto3" json:"Repo,omitempty"`
	DefaultBranch string `protobuf:"bytes,3,opt,name=DefaultBranch,proto3" json:"DefaultBranch,omitempty"`
	Private       bool   `protobuf:"varint,4,opt,name=Private,proto3" json:"Private,omitempty"`
}

func (x *RepositoryInfo) Reset() {
	*x = RepositoryInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_provider_provider_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepositoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepositoryInfo) ProtoMessage() {}

func (x *RepositoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepositoryInfo.ProtoReflect.Descriptor instead.
func (*RepositoryInfo) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{0}
}

func (x *RepositoryInfo) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *RepositoryInfo) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *RepositoryInfo) GetDefaultBranch() string {
	if x != nil {
		return x.DefaultBranch
	}
	return ""
}

func (x *RepositoryInfo) GetPrivate() bool {
	if x != nil {
		return x.Private
	}
	return false
}

type CreateReleaseConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Changelog  string `protobuf:"bytes,1,opt,name=Changelog,proto3" json:"Changelog,omitempty"`
	NewVersion string `protobuf:"bytes,2,opt,name=NewVersion,proto3" json:"NewVersion,omitempty"`
	Prerelease bool   `protobuf:"varint,3,opt,name=Prerelease,proto3" json:"Prerelease,omitempty"`
	Branch     string `protobuf:"bytes,4,opt,name=Branch,proto3" json:"Branch,omitempty"`
	SHA        string `protobuf:"bytes,5,opt,name=SHA,proto3" json:"SHA,omitempty"`
}

func (x *CreateReleaseConfig) Reset() {
	*x = CreateReleaseConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_provider_provider_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateReleaseConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReleaseConfig) ProtoMessage() {}

func (x *CreateReleaseConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReleaseConfig.ProtoReflect.Descriptor instead.
func (*CreateReleaseConfig) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{1}
}

func (x *CreateReleaseConfig) GetChangelog() string {
	if x != nil {
		return x.Changelog
	}
	return ""
}

func (x *CreateReleaseConfig) GetNewVersion() string {
	if x != nil {
		return x.NewVersion
	}
	return ""
}

func (x *CreateReleaseConfig) GetPrerelease() bool {
	if x != nil {
		return x.Prerelease
	}
	return false
}

func (x *CreateReleaseConfig) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *CreateReleaseConfig) GetSHA() string {
	if x != nil {
		return x.SHA
	}
	return ""
}

type ProviderName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ProviderName) Reset() {
	*x = ProviderName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_provider_provider_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProviderName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderName) ProtoMessage() {}

func (x *ProviderName) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderName.ProtoReflect.Descriptor instead.
func (*ProviderName) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{2}
}

type ProviderName_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ProviderName_Request) Reset() {
	*x = ProviderName_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_provider_provider_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProviderName_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderName_Request) ProtoMessage() {}

func (x *ProviderName_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderName_Request.ProtoReflect.Descriptor instead.
func (*ProviderName_Request) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{2, 0}
}

type ProviderName_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *ProviderName_Response) Reset() {
	*x = ProviderName_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_provider_provider_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProviderName_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderName_Response) ProtoMessage() {}

func (x *ProviderName_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderName_Response.ProtoReflect.Descriptor instead.
func (*ProviderName_Response) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{2, 1}
}

func (x *ProviderName_Response) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_pkg_provider_provider_proto protoreflect.FileDescriptor

var file_pkg_provider_provider_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x2f, 0x70,
	0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x18, 0x70,
	0x6b, 0x67, 0x2f, 0x73, 0x65, 0x6d, 0x72, 0x65, 0x6c, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7a, 0x0a, 0x0e, 0x52, 0x65, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x4f, 0x77, 0x6e,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x52, 0x65, 0x70, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x52,
	0x65, 0x70, 0x6f, 0x12, 0x24, 0x0a, 0x0d, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x42, 0x72,
	0x61, 0x6e, 0x63, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x44, 0x65, 0x66, 0x61,
	0x75, 0x6c, 0x74, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x50, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x22, 0x9d, 0x01, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x6c, 0x65, 0x61, 0x73, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x6c, 0x6f, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x6c, 0x6f, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x4e, 0x65, 0x77,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x4e,
	0x65, 0x77, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x72, 0x65,
	0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x50,
	0x72, 0x65, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x72, 0x61,
	0x6e, 0x63, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x42, 0x72, 0x61, 0x6e, 0x63,
	0x68, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x48, 0x41, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x53, 0x48, 0x41, 0x22, 0x39, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x1a, 0x09, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e,
	0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x32, 0x51,
	0x0a, 0x18, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x12, 0x35, 0x0a, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x15, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x3e, 0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x67, 0x6f, 0x2d, 0x73, 0x65, 0x6d, 0x61, 0x6e, 0x74, 0x69, 0x63, 0x2d, 0x72, 0x65, 0x6c, 0x65,
	0x61, 0x73, 0x65, 0x2f, 0x73, 0x65, 0x6d, 0x61, 0x6e, 0x74, 0x69, 0x63, 0x2d, 0x72, 0x65, 0x6c,
	0x65, 0x61, 0x73, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_provider_provider_proto_rawDescOnce sync.Once
	file_pkg_provider_provider_proto_rawDescData = file_pkg_provider_provider_proto_rawDesc
)

func file_pkg_provider_provider_proto_rawDescGZIP() []byte {
	file_pkg_provider_provider_proto_rawDescOnce.Do(func() {
		file_pkg_provider_provider_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_provider_provider_proto_rawDescData)
	})
	return file_pkg_provider_provider_proto_rawDescData
}

var file_pkg_provider_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_provider_provider_proto_goTypes = []interface{}{
	(*RepositoryInfo)(nil),        // 0: RepositoryInfo
	(*CreateReleaseConfig)(nil),   // 1: CreateReleaseConfig
	(*ProviderName)(nil),          // 2: ProviderName
	(*ProviderName_Request)(nil),  // 3: ProviderName.Request
	(*ProviderName_Response)(nil), // 4: ProviderName.Response
}
var file_pkg_provider_provider_proto_depIdxs = []int32{
	3, // 0: RepositoryProviderPlugin.Name:input_type -> ProviderName.Request
	4, // 1: RepositoryProviderPlugin.Name:output_type -> ProviderName.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_provider_provider_proto_init() }
func file_pkg_provider_provider_proto_init() {
	if File_pkg_provider_provider_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_provider_provider_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepositoryInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_provider_provider_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateReleaseConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_provider_provider_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProviderName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_provider_provider_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProviderName_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_provider_provider_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProviderName_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_provider_provider_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_provider_provider_proto_goTypes,
		DependencyIndexes: file_pkg_provider_provider_proto_depIdxs,
		MessageInfos:      file_pkg_provider_provider_proto_msgTypes,
	}.Build()
	File_pkg_provider_provider_proto = out.File
	file_pkg_provider_provider_proto_rawDesc = nil
	file_pkg_provider_provider_proto_goTypes = nil
	file_pkg_provider_provider_proto_depIdxs = nil
}
