// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: pkg/provider/provider.proto

package provider

import (
	semrel "github.com/go-semantic-release/semantic-release/v2/pkg/semrel"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RepositoryInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Owner         string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Repo          string `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	DefaultBranch string `protobuf:"bytes,3,opt,name=default_branch,json=defaultBranch,proto3" json:"default_branch,omitempty"`
	Private       bool   `protobuf:"varint,4,opt,name=private,proto3" json:"private,omitempty"`
}

func (x *RepositoryInfo) Reset() {
	*x = RepositoryInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_provider_provider_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepositoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepositoryInfo) ProtoMessage() {}

func (x *RepositoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepositoryInfo.ProtoReflect.Descriptor instead.
func (*RepositoryInfo) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{0}
}

func (x *RepositoryInfo) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *RepositoryInfo) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *RepositoryInfo) GetDefaultBranch() string {
	if x != nil {
		return x.DefaultBranch
	}
	return ""
}

func (x *RepositoryInfo) GetPrivate() bool {
	if x != nil {
		return x.Private
	}
	return false
}

type CreateReleaseConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Changelog  string `protobuf:"bytes,1,opt,name=changelog,proto3" json:"changelog,omitempty"`
	NewVersion string `protobuf:"bytes,2,opt,name=new_version,json=newVersion,proto3" json:"new_version,omitempty"`
	Prerelease bool   `protobuf:"varint,3,opt,name=prerelease,proto3" json:"prerelease,omitempty"`
	Branch     string `protobuf:"bytes,4,opt,name=branch,proto3" json:"branch,omitempty"`
	SHA        string `protobuf:"bytes,5,opt,name=SHA,proto3" json:"SHA,omitempty"`
}

func (x *CreateReleaseConfig) Reset() {
	*x = CreateReleaseConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_provider_provider_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateReleaseConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReleaseConfig) ProtoMessage() {}

func (x *CreateReleaseConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReleaseConfig.ProtoReflect.Descriptor instead.
func (*CreateReleaseConfig) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{1}
}

func (x *CreateReleaseConfig) GetChangelog() string {
	if x != nil {
		return x.Changelog
	}
	return ""
}

func (x *CreateReleaseConfig) GetNewVersion() string {
	if x != nil {
		return x.NewVersion
	}
	return ""
}

func (x *CreateReleaseConfig) GetPrerelease() bool {
	if x != nil {
		return x.Prerelease
	}
	return false
}

func (x *CreateReleaseConfig) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *CreateReleaseConfig) GetSHA() string {
	if x != nil {
		return x.SHA
	}
	return ""
}

type ProviderInit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ProviderInit) Reset() {
	*x = ProviderInit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_provider_provider_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProviderInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderInit) ProtoMessage() {}

func (x *ProviderInit) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderInit.ProtoReflect.Descriptor instead.
func (*ProviderInit) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{2}
}

type ProviderName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ProviderName) Reset() {
	*x = ProviderName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_provider_provider_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProviderName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderName) ProtoMessage() {}

func (x *ProviderName) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderName.ProtoReflect.Descriptor instead.
func (*ProviderName) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{3}
}

type ProviderVersion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ProviderVersion) Reset() {
	*x = ProviderVersion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_provider_provider_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProviderVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderVersion) ProtoMessage() {}

func (x *ProviderVersion) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderVersion.ProtoReflect.Descriptor instead.
func (*ProviderVersion) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{4}
}

type GetInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetInfo) Reset() {
	*x = GetInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_provider_provider_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfo) ProtoMessage() {}

func (x *GetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfo.ProtoReflect.Descriptor instead.
func (*GetInfo) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{5}
}

type GetCommits struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetCommits) Reset() {
	*x = GetCommits{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_provider_provider_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCommits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommits) ProtoMessage() {}

func (x *GetCommits) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommits.ProtoReflect.Descriptor instead.
func (*GetCommits) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{6}
}

type GetReleases struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetReleases) Reset() {
	*x = GetReleases{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_provider_provider_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReleases) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReleases) ProtoMessage() {}

func (x *GetReleases) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReleases.ProtoReflect.Descriptor instead.
func (*GetReleases) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{7}
}

type CreateRelease struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateRelease) Reset() {
	*x = CreateRelease{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_provider_provider_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRelease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRelease) ProtoMessage() {}

func (x *CreateRelease) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRelease.ProtoReflect.Descriptor instead.
func (*CreateRelease) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{8}
}

type ProviderInit_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config map[string]string `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ProviderInit_Request) Reset() {
	*x = ProviderInit_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_provider_provider_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProviderInit_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderInit_Request) ProtoMessage() {}

func (x *ProviderInit_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderInit_Request.ProtoReflect.Descriptor instead.
func (*ProviderInit_Request) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ProviderInit_Request) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type ProviderInit_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ProviderInit_Response) Reset() {
	*x = ProviderInit_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_provider_provider_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProviderInit_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderInit_Response) ProtoMessage() {}

func (x *ProviderInit_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderInit_Response.ProtoReflect.Descriptor instead.
func (*ProviderInit_Response) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{2, 1}
}

func (x *ProviderInit_Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ProviderName_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ProviderName_Request) Reset() {
	*x = ProviderName_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_provider_provider_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProviderName_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderName_Request) ProtoMessage() {}

func (x *ProviderName_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderName_Request.ProtoReflect.Descriptor instead.
func (*ProviderName_Request) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{3, 0}
}

type ProviderName_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ProviderName_Response) Reset() {
	*x = ProviderName_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_provider_provider_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProviderName_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderName_Response) ProtoMessage() {}

func (x *ProviderName_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderName_Response.ProtoReflect.Descriptor instead.
func (*ProviderName_Response) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{3, 1}
}

func (x *ProviderName_Response) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ProviderVersion_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ProviderVersion_Request) Reset() {
	*x = ProviderVersion_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_provider_provider_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProviderVersion_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderVersion_Request) ProtoMessage() {}

func (x *ProviderVersion_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderVersion_Request.ProtoReflect.Descriptor instead.
func (*ProviderVersion_Request) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{4, 0}
}

type ProviderVersion_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *ProviderVersion_Response) Reset() {
	*x = ProviderVersion_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_provider_provider_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProviderVersion_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderVersion_Response) ProtoMessage() {}

func (x *ProviderVersion_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderVersion_Response.ProtoReflect.Descriptor instead.
func (*ProviderVersion_Response) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{4, 1}
}

func (x *ProviderVersion_Response) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetInfo_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetInfo_Request) Reset() {
	*x = GetInfo_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_provider_provider_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetInfo_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfo_Request) ProtoMessage() {}

func (x *GetInfo_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfo_Request.ProtoReflect.Descriptor instead.
func (*GetInfo_Request) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{5, 0}
}

type GetInfo_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info  *RepositoryInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Error string          `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetInfo_Response) Reset() {
	*x = GetInfo_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_provider_provider_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetInfo_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfo_Response) ProtoMessage() {}

func (x *GetInfo_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfo_Response.ProtoReflect.Descriptor instead.
func (*GetInfo_Response) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{5, 1}
}

func (x *GetInfo_Response) GetInfo() *RepositoryInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *GetInfo_Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetCommits_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ToSha   string `protobuf:"bytes,1,opt,name=to_sha,json=toSha,proto3" json:"to_sha,omitempty"`
	FromSha string `protobuf:"bytes,2,opt,name=from_sha,json=fromSha,proto3" json:"from_sha,omitempty"`
}

func (x *GetCommits_Request) Reset() {
	*x = GetCommits_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_provider_provider_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCommits_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommits_Request) ProtoMessage() {}

func (x *GetCommits_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommits_Request.ProtoReflect.Descriptor instead.
func (*GetCommits_Request) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{6, 0}
}

func (x *GetCommits_Request) GetToSha() string {
	if x != nil {
		return x.ToSha
	}
	return ""
}

func (x *GetCommits_Request) GetFromSha() string {
	if x != nil {
		return x.FromSha
	}
	return ""
}

type GetCommits_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RawCommits []*semrel.RawCommit `protobuf:"bytes,1,rep,name=raw_commits,json=rawCommits,proto3" json:"raw_commits,omitempty"`
	Error      string              `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetCommits_Response) Reset() {
	*x = GetCommits_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_provider_provider_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCommits_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommits_Response) ProtoMessage() {}

func (x *GetCommits_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommits_Response.ProtoReflect.Descriptor instead.
func (*GetCommits_Response) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{6, 1}
}

func (x *GetCommits_Response) GetRawCommits() []*semrel.RawCommit {
	if x != nil {
		return x.RawCommits
	}
	return nil
}

func (x *GetCommits_Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetReleases_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Regexp string `protobuf:"bytes,1,opt,name=regexp,proto3" json:"regexp,omitempty"`
}

func (x *GetReleases_Request) Reset() {
	*x = GetReleases_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_provider_provider_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReleases_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReleases_Request) ProtoMessage() {}

func (x *GetReleases_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReleases_Request.ProtoReflect.Descriptor instead.
func (*GetReleases_Request) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{7, 0}
}

func (x *GetReleases_Request) GetRegexp() string {
	if x != nil {
		return x.Regexp
	}
	return ""
}

type GetReleases_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Releases []*semrel.Release `protobuf:"bytes,1,rep,name=releases,proto3" json:"releases,omitempty"`
	Error    string            `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetReleases_Response) Reset() {
	*x = GetReleases_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_provider_provider_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReleases_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReleases_Response) ProtoMessage() {}

func (x *GetReleases_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReleases_Response.ProtoReflect.Descriptor instead.
func (*GetReleases_Response) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{7, 1}
}

func (x *GetReleases_Response) GetReleases() []*semrel.Release {
	if x != nil {
		return x.Releases
	}
	return nil
}

func (x *GetReleases_Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CreateRelease_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config *CreateReleaseConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *CreateRelease_Request) Reset() {
	*x = CreateRelease_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_provider_provider_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRelease_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRelease_Request) ProtoMessage() {}

func (x *CreateRelease_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRelease_Request.ProtoReflect.Descriptor instead.
func (*CreateRelease_Request) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{8, 0}
}

func (x *CreateRelease_Request) GetConfig() *CreateReleaseConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type CreateRelease_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *CreateRelease_Response) Reset() {
	*x = CreateRelease_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_provider_provider_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRelease_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRelease_Response) ProtoMessage() {}

func (x *CreateRelease_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_provider_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRelease_Response.ProtoReflect.Descriptor instead.
func (*CreateRelease_Response) Descriptor() ([]byte, []int) {
	return file_pkg_provider_provider_proto_rawDescGZIP(), []int{8, 1}
}

func (x *CreateRelease_Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_pkg_provider_provider_proto protoreflect.FileDescriptor

var file_pkg_provider_provider_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x2f, 0x70,
	0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x18, 0x70,
	0x6b, 0x67, 0x2f, 0x73, 0x65, 0x6d, 0x72, 0x65, 0x6c, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7b, 0x0a, 0x0e, 0x52, 0x65, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x72, 0x65, 0x70, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72,
	0x65, 0x70, 0x6f, 0x12, 0x25, 0x0a, 0x0e, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x62,
	0x72, 0x61, 0x6e, 0x63, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x64, 0x65, 0x66,
	0x61, 0x75, 0x6c, 0x74, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x70, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x22, 0x9e, 0x01, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1c, 0x0a, 0x09,
	0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x6c, 0x6f, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x6c, 0x6f, 0x67, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x65,
	0x77, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x6e, 0x65, 0x77, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x70,
	0x72, 0x65, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0a, 0x70, 0x72, 0x65, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x62,
	0x72, 0x61, 0x6e, 0x63, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x72, 0x61,
	0x6e, 0x63, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x48, 0x41, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x53, 0x48, 0x41, 0x22, 0xb1, 0x01, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64,
	0x65, 0x72, 0x49, 0x6e, 0x69, 0x74, 0x1a, 0x7f, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x39, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x69, 0x74,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x1a, 0x39, 0x0a, 0x0b,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x20, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x39, 0x0a, 0x0c, 0x50, 0x72, 0x6f,
	0x76, 0x69, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x09, 0x0a, 0x07, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x42, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x1a, 0x09, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x24, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x5b, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x1a, 0x09, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x45,
	0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x98, 0x01, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d,
	0x6d, 0x69, 0x74, 0x73, 0x1a, 0x3b, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x15, 0x0a, 0x06, 0x74, 0x6f, 0x5f, 0x73, 0x68, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x53, 0x68, 0x61, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x73,
	0x68, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x72, 0x6f, 0x6d, 0x53, 0x68,
	0x61, 0x1a, 0x4d, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a,
	0x0b, 0x72, 0x61, 0x77, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x52, 0x61, 0x77, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x0a,
	0x72, 0x61, 0x77, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x22, 0x78, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x73, 0x1a,
	0x21, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x67, 0x65, 0x78, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x65,
	0x78, 0x70, 0x1a, 0x46, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24,
	0x0a, 0x08, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x08, 0x2e, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x6c, 0x65,
	0x61, 0x73, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x6a, 0x0a, 0x0d, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x1a, 0x37, 0x0a, 0x07, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x06, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x1a, 0x20, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x32, 0xa5, 0x03, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x76, 0x69,
	0x64, 0x65, 0x72, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x12, 0x35, 0x0a, 0x04, 0x49, 0x6e, 0x69,
	0x74, 0x12, 0x15, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x69, 0x74,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69,
	0x64, 0x65, 0x72, 0x49, 0x6e, 0x69, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x35, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x15, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69,
	0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x16, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x18, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x50,
	0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x10, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x43, 0x6f,
	0x6d, 0x6d, 0x69, 0x74, 0x73, 0x12, 0x13, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x73, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x47, 0x65, 0x74,
	0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3a, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x73, 0x12,
	0x14, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x73, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x6c, 0x65, 0x61,
	0x73, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x0d,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x12, 0x16, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x6c, 0x65, 0x61, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x41,
	0x5a, 0x3f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x2d,
	0x73, 0x65, 0x6d, 0x61, 0x6e, 0x74, 0x69, 0x63, 0x2d, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65,
	0x2f, 0x73, 0x65, 0x6d, 0x61, 0x6e, 0x74, 0x69, 0x63, 0x2d, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73,
	0x65, 0x2f, 0x76, 0x32, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_provider_provider_proto_rawDescOnce sync.Once
	file_pkg_provider_provider_proto_rawDescData = file_pkg_provider_provider_proto_rawDesc
)

func file_pkg_provider_provider_proto_rawDescGZIP() []byte {
	file_pkg_provider_provider_proto_rawDescOnce.Do(func() {
		file_pkg_provider_provider_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_provider_provider_proto_rawDescData)
	})
	return file_pkg_provider_provider_proto_rawDescData
}

var file_pkg_provider_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_pkg_provider_provider_proto_goTypes = []interface{}{
	(*RepositoryInfo)(nil),           // 0: RepositoryInfo
	(*CreateReleaseConfig)(nil),      // 1: CreateReleaseConfig
	(*ProviderInit)(nil),             // 2: ProviderInit
	(*ProviderName)(nil),             // 3: ProviderName
	(*ProviderVersion)(nil),          // 4: ProviderVersion
	(*GetInfo)(nil),                  // 5: GetInfo
	(*GetCommits)(nil),               // 6: GetCommits
	(*GetReleases)(nil),              // 7: GetReleases
	(*CreateRelease)(nil),            // 8: CreateRelease
	(*ProviderInit_Request)(nil),     // 9: ProviderInit.Request
	(*ProviderInit_Response)(nil),    // 10: ProviderInit.Response
	nil,                              // 11: ProviderInit.Request.ConfigEntry
	(*ProviderName_Request)(nil),     // 12: ProviderName.Request
	(*ProviderName_Response)(nil),    // 13: ProviderName.Response
	(*ProviderVersion_Request)(nil),  // 14: ProviderVersion.Request
	(*ProviderVersion_Response)(nil), // 15: ProviderVersion.Response
	(*GetInfo_Request)(nil),          // 16: GetInfo.Request
	(*GetInfo_Response)(nil),         // 17: GetInfo.Response
	(*GetCommits_Request)(nil),       // 18: GetCommits.Request
	(*GetCommits_Response)(nil),      // 19: GetCommits.Response
	(*GetReleases_Request)(nil),      // 20: GetReleases.Request
	(*GetReleases_Response)(nil),     // 21: GetReleases.Response
	(*CreateRelease_Request)(nil),    // 22: CreateRelease.Request
	(*CreateRelease_Response)(nil),   // 23: CreateRelease.Response
	(*semrel.RawCommit)(nil),         // 24: RawCommit
	(*semrel.Release)(nil),           // 25: Release
}
var file_pkg_provider_provider_proto_depIdxs = []int32{
	11, // 0: ProviderInit.Request.config:type_name -> ProviderInit.Request.ConfigEntry
	0,  // 1: GetInfo.Response.info:type_name -> RepositoryInfo
	24, // 2: GetCommits.Response.raw_commits:type_name -> RawCommit
	25, // 3: GetReleases.Response.releases:type_name -> Release
	1,  // 4: CreateRelease.Request.config:type_name -> CreateReleaseConfig
	9,  // 5: ProviderPlugin.Init:input_type -> ProviderInit.Request
	12, // 6: ProviderPlugin.Name:input_type -> ProviderName.Request
	14, // 7: ProviderPlugin.Version:input_type -> ProviderVersion.Request
	16, // 8: ProviderPlugin.GetInfo:input_type -> GetInfo.Request
	18, // 9: ProviderPlugin.GetCommits:input_type -> GetCommits.Request
	20, // 10: ProviderPlugin.GetReleases:input_type -> GetReleases.Request
	22, // 11: ProviderPlugin.CreateRelease:input_type -> CreateRelease.Request
	10, // 12: ProviderPlugin.Init:output_type -> ProviderInit.Response
	13, // 13: ProviderPlugin.Name:output_type -> ProviderName.Response
	15, // 14: ProviderPlugin.Version:output_type -> ProviderVersion.Response
	17, // 15: ProviderPlugin.GetInfo:output_type -> GetInfo.Response
	19, // 16: ProviderPlugin.GetCommits:output_type -> GetCommits.Response
	21, // 17: ProviderPlugin.GetReleases:output_type -> GetReleases.Response
	23, // 18: ProviderPlugin.CreateRelease:output_type -> CreateRelease.Response
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_provider_provider_proto_init() }
func file_pkg_provider_provider_proto_init() {
	if File_pkg_provider_provider_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_provider_provider_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepositoryInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_provider_provider_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateReleaseConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_provider_provider_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProviderInit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_provider_provider_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProviderName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_provider_provider_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProviderVersion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_provider_provider_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_provider_provider_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCommits); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_provider_provider_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReleases); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_provider_provider_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRelease); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_provider_provider_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProviderInit_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_provider_provider_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProviderInit_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_provider_provider_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProviderName_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_provider_provider_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProviderName_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_provider_provider_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProviderVersion_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_provider_provider_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProviderVersion_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_provider_provider_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetInfo_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_provider_provider_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetInfo_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_provider_provider_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCommits_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_provider_provider_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCommits_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_provider_provider_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReleases_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_provider_provider_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReleases_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_provider_provider_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRelease_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_provider_provider_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRelease_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_provider_provider_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_provider_provider_proto_goTypes,
		DependencyIndexes: file_pkg_provider_provider_proto_depIdxs,
		MessageInfos:      file_pkg_provider_provider_proto_msgTypes,
	}.Build()
	File_pkg_provider_provider_proto = out.File
	file_pkg_provider_provider_proto_rawDesc = nil
	file_pkg_provider_provider_proto_goTypes = nil
	file_pkg_provider_provider_proto_depIdxs = nil
}
